version: "3.6"


services:

  traefik_reverse_proxy:
    build: ./www/traefik
    command: --api
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      oidc_network:
        ipv4_address: 172.16.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  oidc_server:
    build: ./www/oidc-server.test/
    restart: on-failure
    networks:
      oidc_network:
        ipv4_address: 172.16.0.3

  oidc_client_hybrid:
    build: ./www/oidc-client-hybrid.test/
    restart: on-failure
    extra_hosts:
      - "oidc-server.test:172.16.0.2"
    networks:
      oidc_network:
        ipv4_address: 172.16.0.5

  oidc_client_js:
    build: ./www/oidc-client-js.test/
    restart: on-failure
    extra_hosts:
      - "oidc-server.test:172.16.0.2"
    networks:
      oidc_network:
        ipv4_address: 172.16.0.7

  oauth2_resources_aspnetcore:
    build: ./www/oauth2-resources-aspnetcore.test/
    restart: on-failure
    extra_hosts:
      - "oidc-server.test:172.16.0.2"
    networks:
      oidc_network:
        ipv4_address: 172.16.0.11

  oauth2_client_aspnetcore:
    build: ./www/oauth2-client-aspnetcore.test/
    restart: on-failure
    extra_hosts:
      - "oidc-server.test:172.16.0.2"
    networks:
      oidc_network:
        ipv4_address: 172.16.0.13


networks:
  oidc_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/18
