logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]
[frontends]
  [frontends.oidc_server]
  backend = "oidc_server"
    [frontends.oidc_server.routes.host]
    rule = "Host:oidc-server.test"
  
  [frontends.oidc_client_hybrid]
  backend = "oidc_client_hybrid"
    [frontends.oidc_client_hybrid.routes.host]
    rule = "Host:oidc-client-hybrid.test"
  
  [frontends.oidc_client_js]
  backend = "oidc_client_js"
    [frontends.oidc_client_js.routes.host]
    rule = "Host:oidc-client-js.test"
  
  [frontends.oauth2_resources_aspnetcore]
  backend = "oauth2_resources_aspnetcore"
    [frontends.oauth2_resources_aspnetcore.routes.host]
    rule = "Host:oauth2-resources-aspnetcore.test"

  [frontends.oauth2_client_aspnetcore]
  backend = "oauth2_client_aspnetcore"
    [frontends.oauth2_client_aspnetcore.routes.host]
    rule = "Host:oauth2-client-aspnetcore.test"


[backends]
  [backends.oidc_server]
    [backends.oidc_server.servers.server1]
    url = "http://172.16.0.3:8003"

  [backends.oidc_client_hybrid]
    [backends.oidc_client_hybrid.servers.server1]
    url = "http://172.16.0.5:8005"

  [backends.oidc_client_js]
    [backends.oidc_client_js.servers.server1]
    url = "http://172.16.0.7:8007"

  [backends.oauth2_resources_aspnetcore]
    [backends.oauth2_resources_aspnetcore.servers.server1]
    url = "http://172.16.0.11:8011"

  [backends.oauth2_client_aspnetcore]
    [backends.oauth2_client_aspnetcore.servers.server1]
    url = "http://172.16.0.13:8013"
